### ISSUE TITLE
sheet_export.py throws a UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by jhanarato** [suttacentral/bilara-data#225]
Over the last few days I've been helping Bhante Khemaratana getting bilara-io running on Windows. I don't have a Windows setup myself to test it. 

He can now run the script `sheet_export.py` and gets the following results:

```C:\Users\learningtoletgo\Documents\GitHub\bilara-data\.scripts>sheet_export.py dn1 dn1.ods
Reading html\pli\ms\sutta\dn\dn1_html.json
Reading reference\pli\ms\sutta\dn\dn1_reference.json
Reading root\pli\ms\sutta\dn\dn1_root-pli-ms.json
Reading translation\en\sujato\sutta\dn\dn1_translation-en-sujato.json
Reading variant\pli\ms\sutta\dn\dn1_variant-pli-ms.json
Traceback (most recent call last):
  File "C:\Users\learningtoletgo\Documents\GitHub\bilara-data\.scripts\sheet_export.py", line 114, in <module>
    pyexcel.isave_as(array=rows, dest_file_name=args.out or (','.join(args.uid) + '.ods'))
  File "C:\Python38\lib\site-packages\pyexcel\core.py", line 101, in isave_as
    return sources.save_sheet(sheet, **dest_keywords)
  File "C:\Python38\lib\site-packages\pyexcel\internal\core.py", line 48, in save_sheet
    return _save_any(a_source, sheet)
  File "C:\Python38\lib\site-packages\pyexcel\internal\core.py", line 60, in _save_any
    a_source.write_data(instance)
  File "C:\Python38\lib\site-packages\pyexcel\plugins\sources\file_output.py", line 32, in write_data
    self._renderer.render_sheet_to_file(
  File "C:\Python38\lib\site-packages\pyexcel\plugins\renderers\excel.py", line 28, in render_sheet_to_file
    save_data(file_name, data, **keywords)
  File "C:\Python38\lib\site-packages\pyexcel_io\io.py", line 126, in save_data
    store_data(
  File "C:\Python38\lib\site-packages\pyexcel_io\io.py", line 148, in store_data
    writer.write(data)
  File "C:\Python38\lib\site-packages\pyexcel_io\book.py", line 220, in write
    sheet_writer.write_array(incoming_dict[sheet_name])
  File "C:\Python38\lib\site-packages\pyexcel_ods3\odsw.py", line 59, in write_array
    to_write_data = list(table)
  File "C:\Python38\lib\site-packages\pyexcel_io\sheet.py", line 63, in to_array
    for row_index, row in enumerate(self.row_iterator()):
  File "C:\Python38\lib\site-packages\pyexcel\plugins\sources\pydata\common.py", line 36, in row_iterator
    for row in self._native_sheet:
  File "C:\Users\learningtoletgo\Documents\GitHub\bilara-data\.scripts\sheet_export.py", line 38, in yield_rows
    file_data = json_load(file)
  File "C:\Users\learningtoletgo\Documents\GitHub\bilara-data\.scripts\common.py", line 79, in json_load
    return json.load(f)
  File "C:\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 28: character maps to <undefined>
```

So when the script reads the file `variant\pli\ms\sutta\dn\dn1_variant-pli-ms.json` it uses the python standard library to load the file at line 79 in `common.py`. As the stack trace shows, python is trying to use the character encoding "CP1252". That's a windows thing:

https://en.wikipedia.org/wiki/Windows-1252

It hits a byte of value 0x81 which does not correspond to anything in that particular encoding. 

I hope this is enough information to solve the problem. 

Cheers,

Ajahn J.R.

**Comment by jhanarato** [comment]
The problem is reproducible on linux. Change line 78 in `common.py` to `with file.open('r', encoding='cp1252') as f:" and you'll see the UnicodeDecodeError.

**Comment by jhanarato** [comment]
OK, this should be the fix. Line 78 should read:

`with file.open('r', encoding='utf-8') as f:`

**Comment by jhanarato** [comment]
So yes, `open()` is platform dependant by design:

https://docs.python.org/3/library/functions.html#open

>  In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding.

**Comment by bandarawela** [comment]
Tested on a windows machine and the fix on line 78 works when exporting as ods and csv. Wonderful!

However when trying to export as .html, (sheet_export.py dn1 dn1.html) this is the result:

```
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u012b' in position 2328: character maps to <undefined>
```

**Comment by jhanarato** [comment]
Can you include the entire output for the command? It looks like the same problem with open() but in a different location. You'll likely come across a number of these throughout the .scripts folder.

**Comment by bandarawela** [comment]
Here it is:

```
C:\GitHub\bilara-data\.scripts>sheet_export.py dn1 dn1.html
Reading html\pli\ms\sutta\dn\dn1_html.json
Reading reference\pli\ms\sutta\dn\dn1_reference.json
Reading root\pli\ms\sutta\dn\dn1_root-pli-ms.json
Reading translation\en\sujato\sutta\dn\dn1_translation-en-sujato.json
Reading variant\pli\ms\sutta\dn\dn1_variant-pli-ms.json
Traceback (most recent call last):
  File "C:\Users\learningtoletgo\Documents\GitHub\bilara-data\.scripts\sheet_export.py", line 114, in <module>
    pyexcel.isave_as(array=rows, dest_file_name=args.out or (','.join(args.uid) + '.ods'))
  File "C:\Python38\lib\site-packages\pyexcel\core.py", line 101, in isave_as
    return sources.save_sheet(sheet, **dest_keywords)
  File "C:\Python38\lib\site-packages\pyexcel\internal\core.py", line 48, in save_sheet
    return _save_any(a_source, sheet)
  File "C:\Python38\lib\site-packages\pyexcel\internal\core.py", line 60, in _save_any
    a_source.write_data(instance)
  File "C:\Python38\lib\site-packages\pyexcel\plugins\sources\file_output.py", line 32, in write_data
    self._renderer.render_sheet_to_file(
  File "C:\Python38\lib\site-packages\pyexcel\renderer.py", line 87, in render_sheet_to_file
    self.render_sheet(sheet, **keywords)
  File "C:\Python38\lib\site-packages\pyexcel_text\textr.py", line 20, in render_sheet
    self._stream.write(content)
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u012b' in position 2328: character maps to <undefined>
```

**Comment by jhanarato** [comment]
Thanks for that. I just took the liberty of submitting a pull request for the first change. Mainly to learn how to do it in future. 

Would you like to work from my repo for now? You can grab it here:

https://github.com/jhanarato/bilara-data

I've not fixed the new problem, only the original problem so the output should be exactly the same as above.

Once things are working well on Windows we can ask Bhante Sujato to merge the changes.

**Comment by sujato** [comment]
Thanks for that, I have asked Blake to review the PR.

On HTML export, I have only really been using the ods export/import, so all other formats should be regarded as untested. If you can find a fix, that would be fantastic!

And if you're bored and looking for something to do, #190 is just sitting there!

**Comment by jhanarato** [comment]
G'day Bhante,

I've done some digging:

The Python team have addressed this issue with a "UTF-8 Mode":

https://www.python.org/dev/peps/pep-0540/

by running a script with the `python -Xutf8` parameter or setting the `PYTHONUTF8=1` environment variable you'll not see the problem and need not change any code. This fix should cover the problem with HTML output which works fine on my Linux box.

This does raise the issue of whether all content files will be UTF-8, but that's a design decision for the SC dev team.

Also, I'm new to pull requests, please let me know if you're happy with my branching, etc.

**Comment by sujato** [comment]
I'm closing this, and in general, yes, all SC files are UTF-8 (except for some eccentricities like Klingon)
